# Generated by Django 4.2.1 on 2023-06-06 13:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(1300)])),
                ('ventilacion', models.CharField(choices=[('acondicionada', 'Acondicionada'), ('ventilador', 'Ventilador')], default='1', max_length=15, verbose_name='Ventilacion')),
                ('temperaturaAgua', models.CharField(choices=[('fria', 'Fría'), ('caliente', 'caliente')], default='1', max_length=10, verbose_name='TemperaturaAgua')),
                ('television', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
                ('idHotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
    ]
