# Generated by Django 4.2.1 on 2023-06-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='temperaturaAgua',
            field=models.CharField(choices=[('fria', 'Fría'), ('caliente', 'Caliente')], default='1', max_length=10, verbose_name='TemperaturaAgua'),
        ),
    ]
