# Generated by Django 4.2.1 on 2023-06-03 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(1300)]),
        ),
    ]
