# Generated by Django 4.2.1 on 2023-06-06 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoDePago', models.CharField(max_length=11)),
                ('fechaDeInicio', models.DateField()),
                ('fechaDeFin', models.DateField()),
                ('monto', models.FloatField()),
                ('pagada', models.BooleanField(default=False)),
                ('idReservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservacion')),
                ('idRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.room')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
